/**
 * The canonical values for every enumerated field in the system.
 *
 * These objects are the single source: the Zod enums in `enums.ts` are built
 * from them, so a value cannot exist in a schema without existing here, and a
 * comparison cannot be written against a value the schema does not accept.
 *
 * The point is not ceremony. `role === 'MANGER'` is a typo the compiler cannot
 * see — it is a valid string, it simply never matches, and the bug shows up as
 * a permission check that silently always fails. `role === ROLE.MANAGER` is a
 * compile error the moment the name is wrong.
 */

export const ROLE = {
  HANDLER: 'HANDLER',
  MANAGER: 'MANAGER',
} as const;

export const DIRECTION = {
  /** Stock arriving. Increases the balance. */
  IN: 'IN',
  /** Stock leaving. Subject to the zero floor. */
  OUT: 'OUT',
} as const;

export const MOVEMENT_TYPE = {
  NORMAL: 'NORMAL',
  /** Negates an earlier movement — the only way to correct a mistake. */
  REVERSAL: 'REVERSAL',
  /** Generated by a physical count, to close the gap with the ledger. */
  STOCK_TAKE_ADJUSTMENT: 'STOCK_TAKE_ADJUSTMENT',
} as const;

export const UNIT = {
  EACH: 'EACH',
  KG: 'KG',
  LITRE: 'LITRE',
  METRE: 'METRE',
  BOX: 'BOX',
  PACK: 'PACK',
} as const;

export const ATTEMPT_OUTCOME = {
  ACCEPTED: 'ACCEPTED',
  REJECTED_INSUFFICIENT_STOCK: 'REJECTED_INSUFFICIENT_STOCK',
  REJECTED_VALIDATION: 'REJECTED_VALIDATION',
  REJECTED_FORBIDDEN: 'REJECTED_FORBIDDEN',
  REJECTED_NOT_FOUND: 'REJECTED_NOT_FOUND',
  REJECTED_CONFLICT: 'REJECTED_CONFLICT',
} as const;

export const ACCESS_CHANGE = {
  GRANTED: 'GRANTED',
  REVOKED: 'REVOKED',
} as const;

export const SORT_ORDER = {
  ASC: 'asc',
  DESC: 'desc',
} as const;

/**
 * Every error this API can return.
 *
 * Clients switch on these, so a renamed code is a breaking change and should
 * look like one. Referencing `ERROR.INSUFFICIENT_STOCK` rather than the string
 * means a rename breaks the build instead of silently falling through to a
 * generic branch at runtime.
 */
export const ERROR = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  FORBIDDEN_LOCATION: 'FORBIDDEN_LOCATION',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  MOVEMENT_NOT_FOUND: 'MOVEMENT_NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ITEM_INACTIVE: 'ITEM_INACTIVE',
  LOCATION_INACTIVE: 'LOCATION_INACTIVE',
  /** The zero floor. Carries `available` so the UI can say how many there are. */
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  ALREADY_REVERSED: 'ALREADY_REVERSED',
  CANNOT_REVERSE_REVERSAL: 'CANNOT_REVERSE_REVERSAL',
  SKU_EXISTS: 'SKU_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  ITEM_HAS_MOVEMENTS: 'ITEM_HAS_MOVEMENTS',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  DUPLICATE: 'DUPLICATE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

/** Tuple forms, for building the Zod enums without repeating the values. */
export const ROLE_VALUES = Object.values(ROLE);
export const DIRECTION_VALUES = Object.values(DIRECTION);
export const MOVEMENT_TYPE_VALUES = Object.values(MOVEMENT_TYPE);
export const UNIT_VALUES = Object.values(UNIT);
export const ATTEMPT_OUTCOME_VALUES = Object.values(ATTEMPT_OUTCOME);
export const ACCESS_CHANGE_VALUES = Object.values(ACCESS_CHANGE);
export const SORT_ORDER_VALUES = Object.values(SORT_ORDER);
export const ERROR_VALUES = Object.values(ERROR);
